### ISSUE TITLE
Huovilainen filter model

### ISSUE THREAD

**Issue by timowest** [ddiakopoulos/MoogLadders#1]
The documentation is not clear about which Huovilainen model is included, the 2004 or simplified 2010 model.

I believe the included simplified model is not the one of the Huovilainen & Välimäki 2010 paper.

**Comment by timowest** [comment]
I just found this implementation of the new Huovilainen model http://song-swap.com/MUMT618/aaron/Presentation/contents.html

Maybe this could be integrated for completeness?

**Comment by ddiakopoulos** [comment]
Great find on that link! If I remember, the present Huovilainen model is based on the 2004 paper from which the an implementation was written by Victor Lazzarini for cSound, and later adapted to more generic C++ by Alessandro Petrolati. I'd love to find time to integrate this model as well... I'll keep this issue open until I do.

**Comment by ddiakopoulos** [comment]
Added as AaronMoog in ea1000845217d2c30251993a84533a2ff2146604
