### ISSUE TITLE
New improved model available

### ISSUE THREAD

**Issue by timowest** [ddiakopoulos/MoogLadders#2]
Just to let you know that there is an improved model by D'Angelo and Välimäki
http://iipl.tk/paper/ICASSP2013/pdfs/0000729.pdf

I haven't yet found a source code version of it.

**Comment by ddiakopoulos** [comment]
I contacted D'Angelo and he provided me with a ref. implementation. This is introduced in 353845aad74957e5ed92e40e15b2c36b875711c0 but I haven't had time to compile it and test yet.

**Comment by timowest** [comment]
I tried this model, but the output is quite silent even with drive = 1 and cutoff + resonance seems to work until 5 - 6 kHz with 44100 Hz sampling rate.

**Comment by ddiakopoulos** [comment]
I did a little tuning and fixing of this filter in a recent update. I haven't tested the response yet, but the gain issue seems fixed.
