### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by stagas** [ddiakopoulos/MoogLadders#5]
Non explicit licensing is protected by copyright law and is considered **All Rights Reserved.** as described [here](http://www.infoworld.com/article/2615869/open-source-software/github-needs-to-take-open-source-seriously.html).

Please add a license file in the repo so we can reuse this awesome work of yours :)

**Comment by ddiakopoulos** [comment]
I edited the readme to reflect the various licenses of the filter implementations. Later, I'll add a licenses file with the full text of each.
