### ISSUE TITLE
MOOGY

### ISSUE THREAD

**Issue by weepy** [ddiakopoulos/MoogLadders#6]
Hey

I found this project and was excited to hear some Moogy sounds. I was disappointed in the filtered white noise output from the Main.cpp app. Am I missing the point somehow ?

Jonah

**Comment by ddiakopoulos** [comment]
I think the readme is quite clear that you should expect filtered white noise. Cheers!

**Comment by weepy** [comment]
Yes sorry. It is. I meant it as a question.  How do you get a Moog  sound
using these filters ;)
