### ISSUE TITLE
Resonance in OberheimVariationMoog cannot be set

### ISSUE THREAD

**Issue by jnicol** [ddiakopoulos/MoogLadders#9]
I have noticed a mistake in the `SetResonance` method of the `OberheimVariationMoog` class:

    virtual void SetResonance(float r) override
    {
        resonance = r;
        K = (4.0) * (Q - 1.0)/(10.0 - 1.0);
    }

The user defined parameter `r` is is never used, and `Q` is used in its place, which has a hard-coded value of `3.0`.

Borrowing from Pirkle's original code, the method should be:

    virtual void SetResonance(float r) override
    {
        // this maps resonance = 1->10 to K = 0 -> 4
        K = (4.0) * (r - 1.0)/(10.0 - 1.0);
    }

If that changes is made then the `Q` member becomes redundant, too.

**Comment by ddiakopoulos** [comment]
Thank you @jnicol - Fixed
